### ISSUE TITLE
利用者は、コマンドpbcopy部分が必要ない

### ISSUE THREAD

**Issue by TomokazuUehara** [Christina-Inching-Triceps/scala-play_handson#18]
以下のコマンド実行時に、

`tree  -L 2 | pbcopy`

で、

` | pbcopy`

部分が不要です〜

**Comment by Christina-Inching-Triceps** [comment]
ありがとうございます。
treeコマンドの部分が自体が不要だったので削除する形で修正をしました。
既にmaster反映済みです。
