### ISSUE TITLE
ループの表現での確認

### ISSUE THREAD

**Issue by TomokazuUehara** [Christina-Inching-Triceps/scala-play_handson#21]
1章4節の「モデルをViewへ渡す」の箇所で、

 val tweets: Seq[Tweet] = (1L to 10).map(i => Tweet(Some(i), s"test tweet${i.toString}"))

で、
　(1L to 10)
は
　(1L to 10L)
か？コードを読んでいるだけ＆動きそうな気もしますが、まだローカルではテストできてないです。
※他の章で 10Lになっている箇所があったので、細かいですが、ご報告まで。

**Comment by Christina-Inching-Triceps** [comment]
フィードバックありがとうございます！
以下のプルリク内で修正しました〜
https://github.com/Christina-Inching-Triceps/scala-play_handson/pull/23
