### ISSUE TITLE
until と to の使い分けについて

### ISSUE THREAD

**Issue by arbol-grande** [Christina-Inching-Triceps/scala-play_handson#6]
重箱の隅をつつくような指摘ですみません。

![image](https://user-images.githubusercontent.com/60130329/76075403-544f0800-5fe0-11ea-8804-c25fccf877f4.png)

で、
`(1L until 10)`
となっていますが、実際に表示されているのは
`(1L to 10)`
での実装かと思われます。

![image](https://user-images.githubusercontent.com/60130329/76075851-12729180-5fe1-11ea-94a1-81a8f0ee3f09.png)

後ほど修正のPull Reqをあげます。

```
scala> (1L until 10) foreach { i =>
     |   println(i)
     | }
1
2
3
4
5
6
7
8
9

scala> (1L to 10) foreach { i =>
     |   println(i)
     | }
1
2
3
4
5
6
7
8
9
10
```

**Comment by Christina-Inching-Triceps** [comment]
ありがとうございます！
markdown側のコードを直し忘れてしまってたみたいです。
それでは修正のプルリクを楽しみにお待ちしております〜
